openmessaging/benchmark

benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
=> Use multiple producer threads to drive the load generation

benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java, driver-api/src/main/java/io/openmessaging/benchmark/driver/BenchmarkProducer.java, driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkDriver.java, driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkProducer.java, driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkProducer.java
=> Use key when publishing messages

.gitignore, driver-kafka/README.md, driver-kafka/deploy/ansible.cfg, driver-kafka/deploy/deploy.yaml, driver-kafka/deploy/provision-kafka-aws.tf, driver-kafka/kafka.yaml, driver-pulsar/README.md, driver-pulsar/deploy/ansible.cfg, driver-pulsar/deploy/deploy.yaml, driver-pulsar/deploy/provision-pulsar-aws.tf, driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkDriver.java
This PR adds `README`s for Pulsar and Kafka, improves the root `README`, and also adds some user-friendliness-oriented changes to the Terraform and Ansible configs.
=> Improve documentation

.gitignore, README.md, driver-kafka/kafka-exactly-once.yaml, driver-kafka/kafka-sync.yaml, driver-kafka/kafka.yaml, driver-pulsar/pulsar-effectively-once.yaml, driver-pulsar/pulsar.yaml
This PR basically streamlines the main README in the repo and delegates benchmarking instructions to the platform-specific READMEs. It also provides a brief description of the project's core goals.
=> README changes

package/src/assemble/bin.xml
This should fix some conflicts in the dependencies
=> Removed individual netty dependencies in favour of netty-all

README.md, driver-pulsar/deploy/deploy.yaml
Currently, we don't provide any guidance on how to actually *interpret* benchmarking results. This PR provides a new section in the README. We'll need more info on this in the coming weeks but this is a decent start.
=> Documentation for interpreting benchmarking output

driver-pulsar/pulsar-effectively-once.yaml, driver-pulsar/pulsar.yaml
=> Use reasonably bigger producer queue size in Pulsar to increase throughput with small messages

benchmark-framework/src/main/java/io/openmessaging/benchmark/Benchmark.java, benchmark-framework/src/main/java/io/openmessaging/benchmark/Workers.java
By having a file based list, we can then pre-create the list with Ansible.
=> Added option to read workers list from config file

driver-kafka/deploy/templates/benchmark-worker.service, driver-kafka/deploy/templates/workers.yaml
This is a fix for openmessaging/openmessaging.github.io#15
=> Added missing distributed deployment files for Kafka

driver-pulsar/deploy/deploy.yaml, driver-pulsar/pom.xml
=> Upgraded Pulsar-1.22

driver-pulsar/deploy/deploy.yaml, driver-pulsar/pom.xml
Reverting because there are conflicts with Jackson versions
This reverts commit df359b5ee48750c82d269e8b16981c30570029b8.
=> Revert "Upgraded Pulsar-1.22 (#38)"

driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkDriver.java
Fixed the error in the first test startup.
=> Catch exception when creating a property that already exists

driver-kafka/deploy/deploy.yaml, driver-pulsar/deploy/deploy.yaml
fix the error when do deploy of pulsar clients.
error messages:
```
TASK [Configure service URL] ****************************************************************************************************************************************************
failed: [54.200.180.26] (item=/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory) => {"changed": false, "item": "/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory", "msg": "Destination /etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory does not exist !", "rc": 257}
failed: [54.245.219.67] (item=/etc/profile.d/lang.sh: line 19: warning: setlocale: …
```
=> Change locale to en_US.utf-8 for all client

driver-pulsar/deploy/deloy_with_stats.yaml
- copy `deploy.yaml` to `deploy_with_stats.yaml`
- revert prometheus/docker changes in `deploy.yaml`.
=> Make prometheus/docker installation optional

.gitignore, benchmark-framework/pom.xml, driver-api/src/main/java/io/openmessaging/benchmark/driver/BenchmarkDriver.java, driver-rocketmq/deploy/ansible.cfg, driver-rocketmq/deploy/deploy.yaml, driver-rocketmq/deploy/provision-rocketmq-alicloud.tf, driver-rocketmq/deploy/templates/benchmark-worker.service, driver-rocketmq/deploy/templates/rmq-broker.properties, driver-rocketmq/deploy/templates/rmq-broker.service, driver-rocketmq/deploy/templates/rmq-namesrv.properties, driver-rocketmq/deploy/templates/rmq-namesrv.service, driver-rocketmq/deploy/templates/workers.yaml, driver-rocketmq/deploy/terraform.tfvars, driver-rocketmq/pom.xml, driver-rocketmq/rocketmq.yaml, driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkConsumer.java, driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkDriver.java, driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkProducer.java, driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/client/RocketMQClientConfig.java, pom.xml
This merge request provides the support for Apache RocketMQ, and only support alicloud at present.
We will support aws later and let other drivers support alicloud.
=> [ISSUE #66] Add apache rocketmq driver for openmessaging-benchmark

driver-pulsar/pom.xml, driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkConsumer.java, driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkDriver.java, driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkProducer.java, driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/config/PulsarClientConfig.java
Upgrading pulsar driver with the latest version of pulsar client 2.1.0-incubating.
This version is backward compatible with pulsar 1.22.0
=> Upgrade pulsar version to 2.1.0-incubating #75

driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqBenchmarkConsumer.java, driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqBenchmarkProducer.java
1、Modify consumer autoAck
2、Modify producer using confirmListener
=> [ISSUE#86]Modify rabbitmq consumer and producer

driver-rabbitmq/rabbitmq.yaml, driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqBenchmarkDriver.java, driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqBenchmarkProducer.java, driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqConfig.java
Message persistence option can be find in rabbitmq.yaml
=> Add RabbitMQ message persistence option

benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java, benchmark-framework/src/main/java/io/openmessaging/benchmark/utils/RandomGenerator.java, benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
Fix [issue](https://github.com/openmessaging/openmessaging-benchmark/issues/128)
=> [ISSUE #128]Fix sub problem

driver-rocketmq/rocketmq.yaml, driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkDriver.java, driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/client/RocketMQClientConfig.java
Fix [issue](https://github.com/openmessaging/openmessaging-benchmark/issues/130)
=> [ISSUE #130]Add rocketmq client args.

driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkConsumer.java
Fix [issue](https://github.com/openmessaging/openmessaging-benchmark/issues/132)
=> [ISSUE #132]Fix kafka consumer problem.

benchmark-framework/src/main/java/io/openmessaging/benchmark/utils/ListPartition.java, benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java
Fix [issue](https://github.com/openmessaging/openmessaging-benchmark/issues/134)
=> [ISSUE #134]Fix NPE problem

driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkDriver.java
Fix [issue](https://github.com/openmessaging/openmessaging-benchmark/issues/136)
=> [ISSUE #136]Close adminClien when stop

driver-kafka/deploy/alicloud/ansible.cfg, driver-kafka/deploy/alicloud/deploy.yaml, driver-kafka/deploy/alicloud/provision-kafka-alicloud.tf, driver-kafka/deploy/alicloud/terraform.tfvars
No change on aws, no side effect if benchmark on aws.
Just chdir to deploy/alicloud before running terraform and deploy operation if you want to benchmark kafka on alicoud.
=> add configuration for benchmarking kafka on alicloud

driver-kafka/deploy/provision-kafka-aws.tf
To be compatible with Terraform 0.12.9
=> Update "aws" and "random" provider versions

benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
The logic to assign producers to workers was incorrect in some combination of producers/workers ratios. Simplified to use simple round-robin assignments of producers to workers to ensure even distribution of traffic in clients.
=> Fixed logic to assign producers to workers

bin/create_charts.py, workloads/1m-10-topics-1-partition-100b.yaml, workloads/1m-10-topics-16-partitions-100b.yaml, workloads/1m-10-topics-2-partitions-100b.yaml, workloads/1m-10-topics-3-partitions-100b.yaml, workloads/1m-10-topics-4-partitions-100b.yaml, workloads/1m-10-topics-6-partitions-100b.yaml, workloads/1m-10-topics-9-partitions-100b.yaml
The workloads used in Pulsar JMS testing.
We created more charts and updated some of the labels.
=> Added Workloads and Additional Charts

driver-pulsar/deploy/deploy.yaml, driver-pulsar/deploy/deploy_with_stats.yaml, driver-pulsar/deploy/provision-pulsar-aws.tf, driver-pulsar/deploy/templates/pulsar_env.sh, driver-pulsar/pom.xml, driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkDriver.java
Update to Pulsar 2.8.1
Update to openjdk11
Use AWS Spot Instances
Configure driver-jms/pulsar drivers
Don't set backlog quota
=> Update driver-pulsar to 2.8.1 and prepare for Pulsar JMS testing

driver-kafka/deploy/ssd-deployment/deploy.yaml, driver-kafka/deploy/ssd-deployment/provision-kafka-aws.tf, driver-kafka/kafka-big-batches-gzip.yaml, driver-kafka/kafka-big-batches-snappy.yaml, driver-kafka/kafka-big-batches-zstd.yaml, driver-kafka/kafka-big-batches.yaml, driver-kafka/kafka-compression-gzip.yaml, driver-kafka/kafka-compression-lz4.yaml, driver-kafka/kafka-compression-snappy.yaml, driver-kafka/kafka-compression-zstd.yaml, driver-kafka/kafka-exactly-once.yaml, driver-kafka/kafka-latency.yaml, driver-kafka/kafka-no-linger.yaml, driver-kafka/kafka-sync.yaml, driver-kafka/kafka-throughput.yaml, driver-pulsar/pulsar.yaml, workloads/1-topic-100-partitions-1kb-4p-4c-2000k.yaml, workloads/1-topic-10000-partitions-1kb-4p-4c-2000k.yaml, workloads/max-rate-1-topic-1-partition-4p-1c-1kb.yaml
- Fix ansible playbook
- Set reset to true to for Kafka driver to make sure cleanup the existing topics
- Add new configuration for Kafka high throughput and low latency
=> Fix the Kafka driver for the deployment for i3en.6xlarge

bin/benchmark, bin/benchmark-worker, deployment/kubernetes/helm/benchmark/templates/benchmark-worker.yaml, deployment/kubernetes/helm/benchmark/templates/benchmark.yaml, deployment/kubernetes/helm/benchmark/values.yaml
Hi 😄 
I've added the ability to control the workers and driver memory configuration via env var.
Also, I've added the ability to override workers k8s resources allocation.
=> Allow users to change memory configurations

docker/Dockerfile.build, docker/README.md
Hi,
I've added an alternative `Dockerfile` without Maven dependency, and documentation about the usage of them.
=> Alternative Dockerfile without Maven dependency

driver-pravega/pom.xml
Reverts openmessaging/benchmark#228
=> Revert "[Pravega Driver] Unable to build benchmark for Pravega Client 0.11.0"

driver-rabbitmq/README.md
* update git repository address
* Cannot create topic with partitions in RabbitMQ, so use 1 partition for rabbitmq
=> Fix RabbitMQ docs (#255)

benchmark-framework/src/main/java/io/openmessaging/benchmark/Workload.java, benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
Controllable option for test warmup: warmupDurationMinutes similar to existing testDurationMinutes.
Default warmupDurationMinutes = 1
In case warmupDurationMinutes = 0 - no warnup, all data will be collected for analysis
=> Test warmup option

driver-pravega/pom.xml
Reverts openmessaging/benchmark#259
=> Revert "[Pravega Driver] [Draft] Update dependencies for Pravega 0.12"

benchmark-framework/pom.xml, pom.xml
Resolve jackson version conflicts
=> [ISSUE #265]Fix com/fasterxml/jackson/annotation/JsonKey: NoClassDefoundError

driver-rocketmq/pom.xml, driver-rocketmq/rocketmq.yaml, driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkDriver.java, driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/client/RocketMQClientConfig.java
=> [ISSUE #268]rocketmq benchmark support acl

benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
fixing https://github.com/openmessaging/benchmark/issues/275
=> [ISSUE#275] Fixing infinite loop waiting for consumers to be ready

driver-rabbitmq/deploy/deploy.yaml, driver-rabbitmq/deploy/terraform.tfvars
To use up to date versions of RabbitMQ
* Updated RHEL version
* Updated Erlang version
* Updated RMQ version
* Disabled GPG checks on RPMs
=> [RabbitMQ] Update software versions

tool/src/main/java/io/openmessaging/benchmark/tool/workload/WorkloadSetTemplate.java
* Template names not honoured
* Expose setter for Jackson
=> [Bugfix] Fix template name handling

.github/workflows/pr-build-and-test.yml, pom.xml
We must regularise the code base to pass the CI checks. However, we should start from a passing baseline before regularisation.
* Build action skips checks
* Fix issues in pom
=> [Bugfix] Temporarily skip checks

.github/workflows/pr-build-and-test.yml, benchmark-framework/src/main/java/io/openmessaging/benchmark/Benchmark.java, benchmark-framework/src/main/java/io/openmessaging/benchmark/ResultsToCsv.java, benchmark-framework/src/main/java/io/openmessaging/benchmark/utils/distributor/KeyDistributor.java, benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java, driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkProducer.java, driver-kop/src/main/java/io/openmessaging/benchmark/driver/kop/config/PulsarConfig.java, driver-kop/src/test/java/io/openmessaging/benchmark/driver/kop/KopBenchmarkDriverTest.java, driver-nats-streaming/src/main/java/io/openmessaging/benchmark/driver/natsStreaming/NatsStreamingBenchmarkConsumer.java, driver-nats-streaming/src/main/java/io/openmessaging/benchmark/driver/natsStreaming/NatsStreamingBenchmarkDriver.java, driver-nats-streaming/src/main/java/io/openmessaging/benchmark/driver/natsStreaming/NatsStreamingBenchmarkProducer.java, driver-pravega/src/main/java/io/openmessaging/benchmark/driver/pravega/config/PravegaConfig.java, driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkConsumer.java, driver-redis/src/main/java/io/openmessaging/benchmark/driver/redis/RedisBenchmarkDriver.java, driver-redis/src/main/java/io/openmessaging/benchmark/driver/redis/RedisBenchmarkProducer.java, driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkConsumer.java, driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkProducer.java, etc/findbugsExclude.xml
Enable detection of common bugs/bad-practices so that we can improve/maintain code quality. See: #314 
* Enabled spotbugs
* Fixed some simple detections
* Excluded non-trivial detections
=> [CI] Enable spotbugs in the build

etc/checkstyle.xml
Partially addresses #313
Sometimes it makes sense to be able to ignore checkstyle warnings
* Enable the SuppressWarnings checkstyle configuration
=> Allow checkstyle to be suppressed in specific cases

benchmark-framework/pom.xml, benchmark-framework/src/main/java/io/openmessaging/benchmark/utils/Timer.java, benchmark-framework/src/main/java/io/openmessaging/benchmark/utils/UniformRateLimiter.java, benchmark-framework/src/test/java/io/openmessaging/benchmark/utils/ListPartitionTest.java, benchmark-framework/src/test/java/io/openmessaging/benchmark/utils/PaddingDecimalFormatTest.java, benchmark-framework/src/test/java/io/openmessaging/benchmark/utils/TimerTest.java, benchmark-framework/src/test/java/io/openmessaging/benchmark/utils/UniformRateLimiterTest.java, driver-kafka/pom.xml, pom.xml
This project is distributed and performs statistical computations which might be deemed significant. Therefore, to provide confidence in the metrics it produces it would be useful for there to be reasonable test coverage.
* Some simple tests targeting timing and reporting of data
* Factored out test dependencies
=> [Unit Tests] Basic tests 1

benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
When running a backlog drain workload, if the time to build and drain the backlog exceeds the `testDurationMinutes` then the benchmark will immediately terminate when the drain is complete. This can truncate the collection of useful metrics.
* Keep running the benchmark for `testDurationMinutes` after the backlog has been drained.
=> Keep running for testDurationMinutes after a backlog drain

benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
Max-sustainable rate was broken in one of the recent refactors
Recreate the `MessageProducer` in the worker when the publish rate is adjusted
=> Fix adjustments of the the max sustainable rate

driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqConfig.java
Allow benchmarking of RMQ streams
* Added `stream` queue type
=> [RMQ] Stream type

driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqBenchmarkDriver.java
In a cluster, we'd like for clients to failover to other brokers in the advent of a broker failure.
* Create clients so that they are aware of all brokers
* Preserve round-robin distribution of topics
* Ensure that failovers will be evenly distributed across cluster brokers
When given a list of broker addresses, clients will try them in the order that they are provided.
=> [RMQ] Clients require all broker addresses to fail over

driver-pulsar/deploy/ssd/deploy.yaml, driver-pulsar/deploy/ssd/extra_vars.yaml, driver-pulsar/pom.xml
Use latest version of systems so that tests present the current state.
* Upgraded to Pulsar 2.10.2
=> [Improvement] Pulsar 2.10.2

pom.xml
This allows the CI tests to pass
=> Bump log4j from 2.17.1 to 2.20.0

driver-rocketmq/pom.xml, driver-rocketmq/rocketmq.yaml, driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkDriver.java, driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/client/RocketMQClientConfig.java
1. update rocketmq core to 5.1.4
2. support batchCQ
3. support autoBatch
4. support backpressure
=> Update rocketmq engine
