openmessaging/benchmark

- README.md
- driver-kafka/deploy/ansible.cfg
- driver-kafka/deploy/provision-kafka-aws.tf
- driver-pulsar/deploy/ansible.cfg
- driver-pulsar/deploy/deploy.yaml
- driver-pulsar/deploy/provision-pulsar-aws.tf
This PR creates a Terraform [output](https://www.terraform.io/intro/getting-started/outputs.html) for both the Pulsar and Kafka setups that enables you to seamlessly SSH into the client hosts with a single command.
> Simplify SSHing into client hosts

- .gitignore
- driver-kafka/README.md
- driver-kafka/deploy/provision-kafka-aws.tf
- driver-kafka/deploy/terraform.tfvars
- driver-pulsar/README.md
- driver-pulsar/deploy/provision-pulsar-aws.tf
- driver-pulsar/deploy/terraform.tfvars
This PR makes a few changes:
* Adds a handful of variables to the Terraform configs (AWS region, instance types, number of instances of ZK/Pulsar/Kafka, etc.) and stores the defaults in a `.tfvars` file (users can change values if they wish to alter the Terraform setup).
* Adds some missing docs re: Ansible deployment to the Kafka and Pulsar READMEs.
> Alter Terraform config to allow for variables

- driver-pulsar/deploy/deploy.yaml
Fixed a couple of issues: 
* regex was not working because of space differences
* We should replace the `serviceUrl` string in all *.yaml files
> Fixed Ansible replacement of serviceUrl in pulsar.yaml

- benchmark-framework/pom.xml
- benchmark-framework/src/main/java/io/openmessaging/benchmark/Benchmark.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/BenchmarkWorker.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/Worker.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/WorkerHandler.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/ConsumerAssignment.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/CountersStats.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/CumulativeLatencies.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/PeriodStats.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/ProducerWorkAssignment.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/TopicSubscription.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/TopicsInfo.java
- bin/benchmark-worker
Added distributed benchmark worker implementation. 
There is a new command `benchmark-worker` which spins up a process that list on an HTTP port and wait for instructions. 
The regular `benchmark` tool can work in 2 ways: 
* Without any specified worker, it will do everything in a single JVM process as before
* When passing a list of workers, it will use those to handle all the producers/consumers.
When running in distributed mode, the `benchmark` tool will take care of coordinating the workers and collecting all the stats to provide a single JSON result for the run.
cc/ @tsypuk
> Distributed benchmark worker implementation

- driver-kafka/deploy/deploy.yaml
- driver-kafka/deploy/provision-kafka-aws.tf
- driver-kafka/deploy/terraform.tfvars
- driver-pulsar/deploy/deploy.yaml
- driver-pulsar/deploy/provision-pulsar-aws.tf
- driver-pulsar/deploy/templates/benchmark-worker.service
- driver-pulsar/deploy/templates/workers.yaml
- driver-pulsar/deploy/terraform.tfvars
Provision multiple small VMs for clients and configure to spin up `benchmak-worker` process in each of them. 
Prefills `workers.yaml` file with the list of available workers.
> Added terraform & ansible scripts to run the benchmark from multiple clients

- driver-kafka/deploy/provision-kafka-aws.tf
- driver-pulsar/deploy/provision-pulsar-aws.tf
In this PR, I've used the `random_id` resource type for Terraform to add a random component to resource names that may be subject to naming clashes. I've also changed away from usage of the `default` name, which can also cause problems.
> Add random hash to AWS resource names to avoid name conflicts

- driver-rabbitmq/rabbitmq.yaml
- workloads/1-topic-1-partition-100b.yaml
- workloads/1-topic-1-partition-1kb.yaml
- workloads/1-topic-16-partitions-1kb.yaml
- workloads/1-topic-3-partition-100b-3producers.yaml
- workloads/backlog-1-topic-1-partition-1kb.yaml
- workloads/backlog-1-topic-16-partitions-1kb.yaml
- workloads/max-rate-1-topic-1-partition-100b.yaml
- workloads/max-rate-1-topic-1-partition-1kb.yaml
- workloads/max-rate-1-topic-100-partitions-100b.yaml
- workloads/max-rate-1-topic-100-partitions-1kb.yaml
- workloads/max-rate-1-topic-16-partitions-100b.yaml
- workloads/max-rate-1-topic-16-partitions-1kb.yaml
- workloads/simple-workload.yaml
This PR fixes one incorrect `name` for a workload and removes extraneous spaces before colons (spaces before colons are _not_ standard YAML)
> Fix YAML oddities

- driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkDriver.java
In the workloads that are building backlog, the producer can get blocked because the quota is exceeded. We should use infinite quota size.
> Set unlimited backlog quota in test to avoid producer getting blocked

- benchmark-framework/src/main/java/io/openmessaging/benchmark/Benchmark.java
If neither workers file nor workers is specified, try to read from the wokers.yaml file if it exists.
> Make distributed mode default. 

- benchmark-framework/pom.xml
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java
- driver-pulsar/deploy/deploy.yaml
- driver-pulsar/pom.xml
- pom.xml
- use *original* versions for 1.22.0-incubating, because 1.22.0-incubating has issues on shaded `pulsar-client-admin` due to apache/incubator-pulsar#1370
- explictly specify `jackson-jaxrs-base` and `jackson-jaxrs-json-provider` (see https://stackoverflow.com/questions/38016192/how-to-use-jersey-with-a-newer-version-of-jackson)
- fix the wrong version of jackson
> Upgrade pulsar version to 1.22.0-incubating

- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
`endToEndLatencyMicros` is calculated based on time difference of `System.currentTimeMillis()` on two different machines. It can be negative.
> Avoid adding negative metric values

- driver-pulsar/deploy/deploy.yaml
- driver-pulsar/deploy/deploy_with_stats.yaml
when do pulsar benchmark, it will meet "out of memory", because benchmark worker takes too much memory and not left enough to system.  Do this change to left enough memory to system.
> change benchmark worker memory from 12GB to 6GB for Pulsar driver

- benchmark-framework/src/main/java/io/openmessaging/benchmark/utils/distributor/KeyDistributor.java
When selecting the `NO_KEY` message distributor, we were incorrectlingly still picking `KeyRoundRobin` distributor.
> Fixed choice of implementation for NoKeyDistributor

- driver-bookkeeper/pom.xml
- pom.xml
As far as I can tell, these versions have been released - consider using
them instead of the SNAPSHOT versions?
(This also makes mvn install work, fixing #64)
> Change POM to not use snapshot releases

- driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkDriver.java
I fixed wrong namespace.
```
09:02:33.852 [main] INFO - Created Pulsar namespace benchmark/dev-cluster/benchmark/dev-cluster/openmessaging-wh08UjI
↓
09:12:57.610 [main] INFO - Created Pulsar namespace benchmark/dev-cluster/openmessaging-tdKRgAc
```
> Fix pulsar driver log

- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java
ObjectMapper parameter JsonFactory should not be YAMLFactory in DistributedWorkersEnsemble.java, it will bring a request timeout when analyzing json content from workers
> [ISSUE#85]Fix request timeout

- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
1、AdjustPublishRate can be very small sometimes (for example 0.001msg/s);
2、RateLimiter will make publisher do nothing during the sampling period；
3、Client-host will send a more small publishRate to worker according to sampling result;
4、SO publish rate always zero.
And we set the min publish rate not less than 1.0msg/s can fix it.(sampling period 10s
)
> [ISSUE#84] Fix zero publish rate

- driver-kafka/kafka-exactly-once.yaml
This driver will cause error while running benchmark.
> Fix tab typo in kafka-exactly-once.yaml

- driver-pulsar/deploy/deploy.yaml
- driver-pulsar/deploy/templates/bookkeeper.conf
- driver-pulsar/pom.xml
- driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkDriver.java
The issue that met:
- binary file download too slow
- Bookie config error for logSizeLimit
- npe in PulsarBenchmarkDriver.java
> Fix current config errors for pulsar config, update pulsar to use 2.1.1

- driver-bookkeeper/deploy/deploy.yaml
- driver-bookkeeper/deploy/terraform.tfvars
- driver-kafka/deploy/deploy.yaml
- driver-pulsar/deploy/deploy.yaml
- driver-pulsar/deploy/templates/bookkeeper.conf
This PR includes changes:
- fix generating bootstrap & zk servers (some ansiable version will generate servers with duplicated ports)
- fix pulsar jvm settings to be aligned with settings of kafka
- tune bookkeeper performance settings
> Fix benchmark on generating bootstrap & zk servers and adjust pulsar settings

- driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkDriver.java
- driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkProducer.java
Topic is bound with producer in RocketMQ-driver while it should be bound with message just as Kafka-driver does.
The way RocketMQ driver create producer for topics should be modified
> Modify the way RocketMQ driver create producer for topics

- driver-kafka/deploy/deploy.yaml
- driver-kafka/deploy/templates/server.properties
Configure both disks in Kafka deployment.
Another options could be to use software RAID-0 to get one logical volume.
cc/ @revans2
> Configure both disks in Kafka deployment

- driver-pulsar/deploy/deploy.yaml
The old version (2.1.1-incubating) was failing to download during the ansible run. I updated to the latest version (2.3.1) and it worked fine.
> Update to latest Pulsar version

- benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
- driver-pulsar/deploy/deploy.yaml
- driver-pulsar/deploy/deploy_with_stats.yaml
- driver-pulsar/deploy/templates/chrony.conf
- driver-pulsar/pulsar-effectively-once.yaml
- driver-pulsar/pulsar.yaml
- driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkDriver.java
- driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/config/PulsarClientConfig.java
In order to get the Pulsar driver to work with 2.4.0, I made the following changes:
- Remove the assumption that the cluster name is part of the namespace/topic name. Prior to PIP-10, the cluster name was part of the namespace/topic name. This was confusing for new users who are used to the new naming convention and it doesn't play nice with the REST admin interface.
- Changed the global-zookeeper option to configuration-store to match the new name
I also fixed the benchmark calculations for aggregate end-to-end latency. Unlike all the other latency calculations, those were being reported in microseconds, not milliseconds.
> Update Pulsar drivers to work with 2.4.0 plus fix aggregate latency

- driver-kafka/deploy/deploy.yaml
- driver-kafka/deploy/templates/chrony.conf
- workloads/1-topic-16-partition-100b.yaml
- workloads/1-topic-6-partition-100b.yaml
In this PR, I have made the following updates for the Kafka driver:
- Updated the Kafka version to the latest stable release, 2.3.0
- Fixed a bug in the Ansible playbook that was setting the bootstrap servers incorrectly
- Added chrony configuration to sync the clients using AWS Time Sync Service. This gives more trustworthy results for the end-to-end latency results.
- Added some new workload inspired by [Benchmarking Apache Kafka: 2 Million Writes Per Second (On Three Cheap Machines)](https://engineering.linkedin.com/kafka/benchmarking-apache-kafka-2-million-writes-second-three-cheap-machines) on the LinkedIn Engineering blog
I have run several iterations of the Kafka benchmarks using these code changes without experiencing any issues.
> Updates for Kafka

- driver-pulsar/pom.xml
While the pulsar broker in the Ansible deployment was updated, the client was still using a very old library.
> Updated pulsar client to 2.4.1

- bin/benchmark-worker
Using exec when running the benchmark inside the container will make sure the `SIGQUIT` to pid 1 is correctly passed to the JVM instead of the bash process.
> Use exec when starting JVM

- benchmark-framework/pom.xml
- driver-pulsar/pom.xml
- driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkDriver.java
- pom.xml
Update some third party libraries:
- Pulsar to 2.8.0
- BookKeeper to 4.14.0
- Jetty to 9.4.42.v20210604
With this fix I am also fixing the BenchmarkWorker that does not work anymore, failing with this error:
```
Jul 26 07:18:49 localhost benchmark-worker: 07:18:49.928 [main] INFO - Logging initialized @1934ms to org.eclipse.jetty.util.log.Slf4jLog
Jul 26 07:18:49 localhost benchmark-worker: Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/util/component/AttributeContainerMap
Jul 26 07:18:49 localhost benchmark-worker: at org.eclipse.jetty.server.Server.<init>(Server.java:79)
Jul 26 07:18:49 localhost benchmark-worker: at org.eclipse.jetty.server.Server.<init>(Server.java:122)
Jul 26 07:18:49 localhost benchmark-worker: at …
```
> Update Pulsar to 2.8.0 and fix Benchmark worker

- benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
Use "MB" to correct the data unit "Mb" to avoid misunderstandings.
> [ENHANCEMENT] data unit correction

- README.md
- benchmark-framework/pom.xml
- driver-redis/pom.xml
- driver-redis/redis.yaml
- driver-redis/src/main/java/io/openmessaging/benchmark/driver/redis/RedisBenchmarkConsumer.java
- driver-redis/src/main/java/io/openmessaging/benchmark/driver/redis/RedisBenchmarkDriver.java
- driver-redis/src/main/java/io/openmessaging/benchmark/driver/redis/RedisBenchmarkProducer.java
- driver-redis/src/main/java/io/openmessaging/benchmark/driver/redis/client/RedisClientConfig.java
- pom.xml
This PR kick-off the Redis support via redis [streams](https://redis.io/topics/streams-intro). 
Here's a quick one-liner:
```bash
$ git clone https://github.com/openmessaging/openmessaging-benchmark
$ cd openmessaging-benchmark
$ mvn install
$ bin/benchmark --drivers driver-redis/redis.yaml workloads/1-topic-1-partition-1kb.yaml
```
> Initial Redis Streams support

- benchmark-framework/pom.xml
- benchmark-framework/src/main/java/io/openmessaging/benchmark/Benchmark.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
- pom.xml
netty-all dependency needed update for openjdk11 support due to reflection errors in coordinating with workers
In testing Kafka JMS  (Confluent JMS Client) ensureTopicsAreReady could infinite loop. The benchmark started better creating the producers before the consumers.
In testing Pulsar Fast JMS (Starlight for JMS) we needed more consumers to get the messages per second throughput we wanted.
> Benchmark and worker fixes and enhancements

- driver-jms/README.md
- driver-jms/kafka-jms.yaml
- driver-jms/package-kafka.sh
- driver-jms/package-pulsar.sh
- driver-jms/src/main/java/io/openmessaging/benchmark/driver/jms/JMSBenchmarkConsumer.java
- driver-jms/src/main/java/io/openmessaging/benchmark/driver/jms/JMSBenchmarkProducer.java
- driver-jms/src/main/java/io/openmessaging/benchmark/driver/jms/JMSBenchmarkTransactionProducer.java
Instructions and scripts for adding in JMS Clients to the OMB tarball.
Allow the JMS connection to close the consumer and session.
Track Latency via a message property
> Prepare driver-jms for Pulsar and Kafka JMS benchmarks

- .gitignore
- driver-pulsar/src/main/java/io/openmessaging/benchmark/driver/pulsar/PulsarBenchmarkDriver.java
- driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqBenchmarkDriver.java
- driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqBenchmarkProducer.java
If the connection failed to be established in `initialize`, and `close` is called (for instance through the `/stop-all` endpoint), an NPE occurs because `connection` is null.
> Fix NPE in RabbitMQ driver

- driver-bookkeeper/deploy/terraform.tfvars
- driver-kafka/deploy/ssd-deployment/deploy.yaml
- driver-kafka/deploy/ssd-deployment/templates/kafka.service
- driver-kafka/deploy/ssd-deployment/terraform.tfvars
- driver-pravega/deploy/terraform.tfvars
- driver-pulsar/deploy/ssd/deploy_with_stats.yaml
- driver-pulsar/deploy/ssd/templates/bookkeeper-skip-journal.conf
- driver-pulsar/deploy/ssd/templates/bookkeeper.conf
- driver-pulsar/deploy/ssd/terraform.tfvars
- driver-rabbitmq/deploy/terraform.tfvars
- workloads/1-topic-100-partitions-1kb-4p-4c-1000k.yaml
- workloads/1-topic-100-partitions-1kb-4p-4c-200k.yaml
- workloads/1-topic-100-partitions-1kb-4p-4c-500k-backlog.yaml
- workloads/1-topic-100-partitions-1kb-4p-4c-500k.yaml
- workloads/1-topic-10000-partitions-1kb-4p-4c-1000k.yaml
- workloads/1-topic-10000-partitions-1kb-4p-4c-200k.yaml
- workloads/1-topic-10000-partitions-1kb-4p-4c-500k.yaml
- Use i3en.6xlarge for Pulsar and Kafka broker
- Use m5n.8xlarge for Client to avoid the client side bottleneck
- Use ZGC for test client
- Add more workloads
> Use i3en.6xlarge for Pulsar and Kafka

- driver-pravega/pom.xml
Hello,
This PR resolves https://github.com/openmessaging/benchmark/issues/227.
As stated within mentioned GitHub issue, I would suggest to merge the changes once Pravega 0.11.0 (or any other version containing updated gRPC dependency) is released. Until the release, this PR could be used to run OpenMessaging benchmark with current master branch of [Pravega](http://github.com/pravega/pravega).
> [Pravega Driver] Unable to build benchmark for Pravega Client 0.11.0

- benchmark-framework/src/main/java/io/openmessaging/benchmark/Benchmark.java
It is convenient to customize the name and path of the output file, and it is convenient to encapsulate the script for testing
> support `--output` parameter

- driver-rabbitmq/deploy/deploy.yaml
* Fix RabbitMQ dl link (not available anymore on bintray)
* Update RabbitMQ to 3.9.11
* Use JDK11
* Add missing java package on client
> Fix RabbitMQ ansible playbook

- driver-kafka/deploy/hdd-deployment/templates/server.properties
- driver-kafka/deploy/ssd-deployment/deploy.yaml
- driver-kafka/deploy/ssd-deployment/templates/server.properties
- Update Kafka version to the latest 3.0.0
- Apply the [confluent configurations](https://github.com/confluentinc/openmessaging-benchmark/blob/master/driver-kafka/deploy/templates/server.properties#L29-L35)
> Update Kafka version to 3.0.0 and applies confluent configurations

- driver-pulsar/deploy/ssd/templates/benchmark-worker.service
- driver-rabbitmq/deploy/deploy.yaml
- driver-rabbitmq/deploy/templates/benchmark-worker.service
- driver-rabbitmq/deploy/templates/chrony.conf
- driver-rabbitmq/deploy/templates/rabbitmq-env.conf
- driver-rabbitmq/deploy/terraform.tfvars
- driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqBenchmarkDriver.java
* Add benchmark-worker service
* Mount and use the same SSD as in other benchmarks
* Remove useless java installation on RabbitMQ nodes
* Setup chrony on clients
> Support for multiple RabbitMQ clients

- deployment/kubernetes/helm/benchmark/templates/benchmark.yaml
On https://github.com/openmessaging/benchmark/pull/220 , I've added the ability to override memory `Xmx` and `Xms` but missed a dash on the default values.
Sorry for that 😅
> Fix missing dash

- driver-pulsar/deploy/ssd/templates/pulsar-dashboard.service
Currently, we are using pull the latest apache pulsar grafana dashboard, but using 0.0.8 to run it, we should run the latest version of apache pulsar grafana dashboard.
* Use the latest apache pulsar grafana dashboard
> Use the latest apache pulsar grafana dashboard

- benchmark-framework/pom.xml
- driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkConsumer.java
- driver-kop/kafka_to_kafka.yaml
- driver-kop/kafka_to_pulsar.yaml
- driver-kop/pom.xml
- driver-kop/pulsar_to_kafka.yaml
- driver-kop/src/main/java/io/openmessaging/benchmark/driver/kop/KopBenchmarkDriver.java
- driver-kop/src/main/java/io/openmessaging/benchmark/driver/kop/config/ClientType.java
- driver-kop/src/main/java/io/openmessaging/benchmark/driver/kop/config/Config.java
- driver-kop/src/main/java/io/openmessaging/benchmark/driver/kop/config/PulsarConfig.java
- driver-kop/src/test/java/io/openmessaging/benchmark/driver/kop/KopBenchmarkDriverTest.java
- driver-kop/src/test/resources/kop_custom.yaml
- driver-kop/src/test/resources/kop_required.yaml
- driver-kop/src/test/resources/kop_wrong_kafka_config.yaml
- pom.xml
Contributed a new driver for KoP (aka. Kafka-on-Pulsar) (https://github.com/streamnative/kop).
KoP enables Kafka applications access a Pulsar cluster. In addition, it also supports the interaction between a Kafka client and a Pulsar client. However, the benchmark cannot test this case, including Kafka producer with Pulsar consumer, or Pulsar producer with Kafka consumer. Therefore, this PR adds a driver to support this case.
- Add a `driver-kop` module, which supports a new configuration format to specify the client type (`kafka` or `pulsar`) of producers and consumers.
- Add a simple unit test for the new configuration format.
- Add three example configuration files under `driver-kop` directory.
- Reuse the existing benchmark producer and consumer from `driver-kafka` and `driver-pulsar`. …
> Create a benchmark driver for KoP (https://github.com/streamnative/kop)

- driver-pulsar/deploy/ssd/provision-pulsar-aws.tf
- driver-pulsar/deploy/ssd/terraform.tfvars
Recently when I modified the `terraform.tfvars` to use AWS CN and find the deployment failed.
> Error: Error launching source instance: Unsupported: Your requested instance type (t2.small) is not supported in your requested Availability Zone (cn-north-1d). Please retry your request by not specifying an Availability Zone or choosing cn-north-1a, cn-north-1b.
However, I've configured the `az` variable with `cn-north-1a` (not `cn-north-1d`) in `terraform.tfvars`. And then I find the `az` is never used. It should be specified when creating a subnet.
In addition, when I ran `terraform init`, I found some warnings:
```
**Warning:** **Interpolation-only expressions are deprecated**
on provision-pulsar-aws.tf line 2, in provider "aws":
2:  region = "${var.region}"
Terraform 0.11 and earlier …
```
> [Pulsar] Fix available zone not configured and clean up the terraform script

- driver-pravega/pom.xml
Hello,
This PR resolves https://github.com/openmessaging/benchmark/issues/258
I would like to mention that [Pravega 0.12.0](https://github.com/pravega/pravega) is currently under development, thus I would like the PR to remain in "draft" status until it would be officially release.
At the same time, it might be a useful source of information for people who would like to try OpenMessaging benchmark with recent versions of Pravega - they would know which parameters (dependencies) should be changed in order to build it with matching client libraries.
> [Pravega Driver] [Draft] Update dependencies for Pravega 0.12

- benchmark-framework/src/main/java/io/openmessaging/benchmark/TestResult.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/utils/UniformRateLimiter.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/WorkerHandler.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/CumulativeLatencies.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/PeriodStats.java
- bin/create_charts.py
This is fixing Coordinated Omission by providing an additional metric ie `producer delay`: this metric should capture the delay while producing the load due to "some reason" (see https://github.com/openmessaging/benchmark/issues/247) preventing the generator to keep up with the expected configured rate.
This change is using a more appropriate rate limiter (different from the one of Guava) that's aware of the expected schedule.
The current strategy to find the sustainable rate (according to a specific backlog) is fine-ish to prevent it to happen, but actual measurements should be taken to check what happen during the actual test too.
> Fixes #247 Fix Coordinated Omission

- benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
Following the issue #275 already closed, I believe that it is better to throw an exception when the timeout is reached instead of logging a warning.
I got an issue after the time out is reached but the test is launched. After the test execution when calling `stop-all` it throws an exception because the time out was a warning telling us that something was not correctly set up.
```
15:56:08  13:56:08.822 [main] INFO - Pub rate    15.1 msg/s /  7.5 MB/s | Cons rate     9.9 msg/s /  5.0 MB/s | Backlog:  4.7 K | Pub Latency (ms) avg: 20.1 - 50%: 14.8 - 99%: 89.2 - 99.9%: 122.4 - Max: 122.4 | Pub Delay Latency (us) avg: 134.7 - 50%: 132.0 - 99%: 200.0 - 99.9%: 209.0 - Max: 209.0
15:56:21  13:56:19.002 [main] INFO - Pub rate    14.9 msg/s /  7.5 MB/s | Cons rate    10.3 msg/s /  5.2 MB/s | …
```
> [issue #275] fix waiting for consumers to be ready

- driver-kafka/deploy/ssd-deployment/deploy.yaml
- driver-kafka/deploy/ssd-deployment/templates/zookeeper.properties
- driver-kafka/deploy/ssd-deployment/templates/zookeeper.service
- driver-kafka/deploy/ssd-deployment/terraform.tfvars
- driver-pulsar/deploy/ssd/deploy.yaml
- driver-pulsar/deploy/ssd/templates/zoo.cfg
- driver-pulsar/deploy/ssd/terraform.tfvars
- Change zookeeper node type to i3en.2xlarge for multi-topics test
- Use separated disks for zookeeper logs and data
- Increase heap memory to 32G to avoid zookeeper OOM during the multi-topics test
I have tested the deployment for both Kafka and Pulsar on AWS.
> Change zookeeper node type to i3en.2xlarge for multi-topics test

- benchmark-framework/pom.xml
Reverts openmessaging/benchmark#274
> Revert "Bump jetty-server from 9.4.42.v20210604 to 10.0.10 in /benchmark-framework"

- driver-rabbitmq/README.md
- driver-rabbitmq/deploy/provision-rabbitmq-aws.tf
- driver-rabbitmq/deploy/terraform.tfvars
Some AZs do not contain the instances type used by the RMQ benchmark client. Therefore it is necessary to explicitly set the AZ to one that does.
* Introduce AZ var
* Default to `us-west-2a`
> [RabbitMQ] Introduce AZ var, default to us-west-2a

- benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java
- benchmark-framework/src/main/resources/log4j2.yaml
- driver-kafka/deploy/ssd-deployment/ansible.cfg
- driver-kafka/kafka-throughput.yaml
- driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaTopicCreator.java
As a new user running benchmarks sometimes it's not clear what's happening at
any given moment. It's useful to add extra logging to give more feedback to the
user. Additionally, the configuration could be more stable under larger
workloads.
* During startup, to test everything is ready a single message is sent from each
producer. The send and received counts are now logged every 2 seconds
* Added rolling-file logging config to allow the user to ssh onto other workers
to check the logs
* Added ServerAliveInterval=60 to the ansible configuration so it's more stable
during long running tasks
* Added request.timeout.ms=1200000 to make Kafka API calls more stable until
larger workloads
* Added periodic logging of Kafka topic creation status
* In DistributedWorkersEnsemble, the use of Pulsar's …
> Improve visibility and stability of benchmark execution

- driver-kafka/deploy/ssd-deployment/deploy.yaml
Sometimes there's a need to update the benchmark code, configuration or workloads or restart Kafka brokers. It can be useful to be able to run a subset of the ansible tasks.
* Add client-code and restart-kafka tags to the Kafka ansible
> Add ansible tags to kafka

- driver-kafka/deploy/ssd-deployment/ansible.cfg
- driver-kafka/deploy/ssd-deployment/provision-kafka-aws.tf
Cleanup Kafka to remove warning and ensure stability
* add Kafka ansible ssh retries
* Replace '-' with '_' in Kafka ansible Name tags to remove warnings
* Add additional tags to easily identify EC2 instances
> Improve Kafka infrastructure stability

- benchmark-framework/src/main/java/io/openmessaging/benchmark/Benchmark.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/Worker.java
If one needs to prematurely terminate a benchmark workload, for example with a Ctrl-C, the workers will no stop. It would be useful to be able to stop the whole workload.
* Add a shutdown hook to call the /stop-all endpoint on all workers
> Add a shutdownhook to stop all workers

- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
- driver-kafka/deploy/ssd-deployment/provision-kafka-aws.tf
- driver-kafka/kafka-big-batches-gzip.yaml
- driver-kafka/kafka-big-batches-lz4.yaml
- driver-kafka/kafka-big-batches-snappy.yaml
- driver-kafka/kafka-big-batches-zstd.yaml
- driver-kafka/kafka-big-batches.yaml
- driver-kafka/kafka-compression-gzip.yaml
- driver-kafka/kafka-compression-lz4.yaml
- driver-kafka/kafka-compression-snappy.yaml
- driver-kafka/kafka-compression-zstd.yaml
- driver-kafka/kafka-exactly-once.yaml
- driver-kafka/kafka-latency.yaml
- driver-kafka/kafka-no-linger.yaml
- driver-kafka/kafka-sync.yaml
- driver-kafka/kafka-throughput.yaml
- driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/Config.java
- driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkDriver.java
The Kafka driver has the ability to `reset` on initialisation which will delete all topics. All workers will attempt to perform this action which can result in contention for resources and UnknownTopicOrPartitionException. This can make it hard to execute workloads, particularly those with lots of topics.
* Remove the Kafka `reset` option
* Expose the Kafka ssh IP address in the terraform to make it easier for users to ssh in to a broker and manually delete topics if needed with the following command `/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --delete --topic test-topic-.*`
* Reorder the Kafka topic names to make selection deletion easier
> Remove Kafka reset option

- benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/utils/Timer.java
It can take time to determine how to scale up backlog drain workloads. How long it takes to build the backlog and drain it are useful pieces of information.
* Add timers to the log of the backlog build up time and backlog drain time
> Add backlog drain timings to the log

- benchmark-framework/src/main/java/io/openmessaging/benchmark/Benchmark.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java
On normal completion, the shutdown hook still executes, but after the http client has been close resulting in exceptions in the log
* Move the shutdown hook into DistributedWorkersEnsemble
* Remove the shutdown hook on close, before the http client is closed.
> Move shutdown hook

- benchmark-framework/pom.xml
- driver-api/pom.xml
- driver-kafka/pom.xml
- driver-kafka/src/test/resources/log4j2.yaml
- driver-kop/src/test/java/io/openmessaging/benchmark/driver/kop/KopBenchmarkDriverTest.java
- pom.xml
- tool/pom.xml
- tool/src/main/resources/log4j2.yaml
log4j-slf4j-simpl and slf4j-simple are both on the classpath in various places which is messing up the logging.
* Replace slf4j-simple with log4j-slf4j-impl
> Cleanup logging

- benchmark-framework/pom.xml
- pom.xml
Keep project dependencies tidy.
Remove unused JUnit4 dependency, especially as we already have JUnit5 and TestNG in the project.
> [Clean-up] Remove unused JUnit 4

- driver-rabbitmq/deploy/deploy.yaml
- driver-rabbitmq/deploy/provision-rabbitmq-aws.tf
It can be useful to simple restart RMQ instances, or to redeploy the client code only.
* Tag tasks for targeted `client-code` deployment, and `restart-rabbitmq` only
* Remove Ansible warning by swapping`-` for `_` in Terraform inventory names
> [RabbitMQ] Clean-up deploy

- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java
The calculation of workers that are actively producing does not correctly account for situations where workers are not allocated any topics. This will occur when the number of topics < number of workers. This results in an artificial reduction in throughput on the active workers.
* Consider only workers with active producers when sharing throughput across workers.
> [Bugfix] Do not allocate throughput to workers with no producers

- benchmark-framework/src/main/java/io/openmessaging/benchmark/Benchmark.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/TestResult.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/DistributedWorkersEnsemble.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/CountersStats.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/commands/PeriodStats.java
- bin/create_charts.py
When a system is at the limits of its performance envelope, it may more readily fall into erroneous states and behaviour quite differently — an open circuit breaker may have a very low latency compared to a message send. Therefore it is desirable to have metrics on producer errors so these conditions can be observed.
* Added `messageSendErrors` counters and accumulators
* Added capture of publish errors
* Updated metrics pathways to include send errors
* Updated loggers, file writers to include send errors
* Charger rendering also outputs error graph
> [Feature] Collect producer error stats

- pom.xml
Partially addresses #313
The current spotless configuration is applies twice with slightly differing results so a `spotless:apply` then fails a `spotless:check`
* Remove md files from the general formats so that only markdown flexmark is applied
> Fix spotless with markdown

- etc/checkstyle.xml
Partially addresses #313
spotless (googleJavaFormat) expects whitespace in an empty for iterator, but checkstyle does not.
* Update checkstyle configuration to allow whitespace
> Allow spaces in empty for iterator

- driver-rabbitmq/README.md
- driver-rabbitmq/deploy/provision-rabbitmq-aws.tf
To observe how the RabbitMQ instances are performing during the benchmark and identify bottlenecks in RMQ.
* Expose management interface publicly (**NOT SECURE**)
* Update README to describe how to access management UI
> [RabbitMQ] Expose management port

- driver-rabbitmq/README.md
- driver-rabbitmq/deploy/deploy.yaml
- driver-rabbitmq/deploy/provision-rabbitmq-aws.tf
- driver-rabbitmq/deploy/templates/grafana-datasource.yml
- driver-rabbitmq/deploy/templates/prometheus.service
- driver-rabbitmq/deploy/templates/prometheus.yml
- driver-rabbitmq/deploy/templates/rabbitmq-dashboard.service
- driver-rabbitmq/deploy/terraform.tfvars
- driver-rabbitmq/rabbitmq.yaml
RabbitMQ performance is quite unpredictable. It would be useful to have internal RMQ and node metrics to better understand bottlenecks.
* Add a monitoring instance
* Install prometheus and grafana on monitoring instance
* Install recommended RMQ dashboards
* Install `node_exporter` and `rabbitmq_prometheus` on all brokers
* Expose prometheus and grafana UI ports
> [RabbitMQ] Prometheus & Grafana

- benchmark-framework/src/main/java/io/openmessaging/benchmark/Workload.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
The ratio of the backlog that can remain and yet the backlog still be considered empty, and thus the workload can complete at the end of the configured duration. In some systems it is not feasible for the backlog to be drained fully and thus the workload will run indefinitely and fail to write out a results file. In such circumstances, one may be content to achieve a partial drain such as 99% of the backlog.
* `backlogDrainRatio` workload option
* Adjust minimum backlog based on configuration
> [Feature] Proportional minimum backlog

- benchmark-framework/src/main/java/io/openmessaging/benchmark/Benchmark.java
- driver-rabbitmq/README.md
- driver-rabbitmq/deploy/alicloud/deploy.yaml
- driver-rabbitmq/deploy/deploy.yaml
- driver-rabbitmq/deploy/templates/rabbitmq-classic.yaml
- driver-rabbitmq/deploy/templates/rabbitmq-quorum.yaml
- driver-rabbitmq/pom.xml
- driver-rabbitmq/rabbitmq.yaml
- driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqBenchmarkDriver.java
- driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqConfig.java
- driver-rabbitmq/src/test/java/io/openmessaging/benchmark/driver/rabbitmq/QueueTypeTest.java
- driver-rabbitmq/src/test/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqConfigTest.java
RabbitMQ supports multiple queue types. We have found behavioural differences between each type. Therefore it is useful for the type to be easily selectable by the user without code changes.
* Introduced `QueueType` enum and configuration field
* Handles field when creating queues
* Related tests
> [RabbitMQ] Queue type configuration option

- driver-rabbitmq/deploy/deploy.yaml
It's useful to be able to deploy the benchmark client code in isolation via ansible. This enables local code changes, but more importantly, the deployment of locally generated workloads.
* Added `file: path=/opt/benchmark state=absent` task prior to client code deployment to clear out any existing install
* Moved the client code deployment section to the end of the file
> [RabbitMQ] Allow deployment of benchmark code in isolation

- driver-artemis/src/main/java/io/openmessaging/benchmark/driver/artemis/ArtemisBenchmarkDriver.java
- driver-artemis/src/main/java/io/openmessaging/benchmark/driver/artemis/ArtemisBenchmarkProducer.java
- see https://activemq.apache.org/components/artemis/documentation/javadocs/javadoc-latest/org/apache/activemq/artemis/api/core/client/SendAcknowledgementHandler.html
- configuring confirmation window is required for async message sending with Artemis
- it is required to use non-blocking sessions for async sends
- The confirmation window size is in bytes, set to 1MB which is a more sensible value.
- configure async acknowledgements
> [fix][artemis] Fix Artemis asynchronous send and acknowledgement configuration

- driver-rabbitmq/deploy/provision-rabbitmq-aws.tf
To run multiple benchmarks concurrently.
* Introduce a random suffix to named resources.
> [RMQ][TF] Use unique deployment resource names

- driver-nats/deploy/provision-nats-aws.tf
To run multiple benchmarks concurrently.
* Introduce a random suffix to named resources.
> [NATS][TF] Use unique deployment resource names

- benchmark-framework/pom.xml
- benchmark-framework/src/main/java/io/openmessaging/benchmark/RateController.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/WorkloadGenerator.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/utils/Env.java
- benchmark-framework/src/test/java/io/openmessaging/benchmark/RateControllerTest.java
- benchmark-framework/src/test/java/io/openmessaging/benchmark/utils/EnvTest.java
- benchmark-framework/src/test/resources/log4j2.yaml
- driver-rocketmq/pom.xml
- pom.xml
Currently the WorkloadGenerator.findMaximumSustainableRate algorithm introduces publish delay. It has been observed the algorithm settles on a publish rate that neither producers nor consumers can keep up with. For example, on a Kafka workload with 100 topics, 1kb message, the algorithm settled on a publish rate of 2.5m msg/s when the producers could only actually achieve 2m msg/s.
Implement a new algorithm that checks for both receive backlog and publish backlog and adjusts the publish according and has a progressive rate ramp up when there is no observed backlog.
> New max sustainable rate implementation

- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/jackson/HistogramDeserializer.java
- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/jackson/HistogramSerializer.java
In some scenarios we hit buffer limits when [de]serialising histograms.
* Increase buffer sizes.
> [Bug] Increase buffer sizes

- driver-nats/deploy/templates/cluster.conf
- driver-nats/nats.yaml
- driver-nats/src/main/java/io/openmessaging/benchmark/driver/nats/NatsBenchmarkDriver.java
To have comparable configurations/behaviours across different messaging systems under test.
* Increase replica count to 3
* Increase timeouts so that system does not so quickly terminate produce calls when under load.
> [NATS] Improve write resiliancy

- driver-rabbitmq/deploy/deploy.yaml
We want to be able to redeploy modified benchmark code to a running system to save setup time.
* Moved benchmark deploy to later in playbook to work more efficiently with `—start-from`
* Added a task to clean folder `/opt/benchmark`
> [RMQ] Allow deployment of benchmark code in isolation

- driver-nats/deploy/deploy.yaml
- driver-nats/pom.xml
- driver-nats/src/main/java/io/openmessaging/benchmark/driver/nats/NatsBenchmarkDriver.java
NATS consumers are erroneously configured only to fan out. We need to be able to distribute messages across multiple consumers as is the case with other drivers.
* Independently create NATS consumers and subscriptions
> [Fix][NATS] Delivery group

- driver-rabbitmq/deploy/deploy.yaml
- driver-rabbitmq/deploy/templates/rabbitmq.conf
To default to consistency in the event of a network partition, as is the expectation with many other systems tested by this benchmark.
* Supply a RabbitMQ server config where in the event of a partition, the cluster will `pause_minority`
> [RMQ] Set partition handling behaviour

- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/LocalWorker.java
- driver-api/src/main/java/io/openmessaging/benchmark/driver/BenchmarkDriver.java
- driver-api/src/main/java/io/openmessaging/benchmark/driver/ResourceCreator.java
- driver-rabbitmq/deploy/templates/rabbitmq-quorum.yaml
- driver-rabbitmq/rabbitmq.yaml
- driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqBenchmarkDriver.java
- driver-rabbitmq/src/main/java/io/openmessaging/benchmark/driver/rabbitmq/RabbitMqConfig.java
- etc/findbugsExclude.xml
Some systems (notably RMQ) struggle to create large volumes of producers/consumers in a short period. This process needs to be more resilient, and to keep attempting to create these resources until they are successful.
* Created a `ResoureCreator` that is based on the earlier `KafkaTopicCreator`
* Use this creator to instantiate consumers and producers in the RMQ driver
* Provide some configuration appropriate for RMQ Quorum Queues
> Resilient resource creation

- benchmark-framework/pom.xml
Fixes issue noted in https://github.com/openmessaging/benchmark/issues/363 , which was blocking me in production as well as locally
Currently the benchmark-framework module is unable to create the worker pool when given a list of workers due to a transitive dependency on netty-transport==4.1.77.Final which is pulled in from the artemis client, which conflicts with asynchttpclient's dependency on netty
This excludes all netty dependencies that the artemis library pulls in which resolves the issue. The artemis driver seems to be functional still without this transitive dependency. 
You can reproduce this issue locally by starting benchmark-worker and attempting to run any benchmark using those workers. Adding the exclusion and rebuilding allows the benchmark to work as intended.
This also …
> Add maven exclusion for netty transitive dependency in artemis

- driver-nats/src/main/java/io/openmessaging/benchmark/driver/nats/NatsBenchmarkDriver.java
- driver-nats/src/main/java/io/openmessaging/benchmark/driver/nats/NatsConfig.java
While I was benchmarking NATS, I found myself needed to benchmark its in-memory stream. 
Think it would be beneficial to other folks with the option. 
Extend `NatsConfig` with `storageType` and `maxBytes` to support in-memory stream while limiting memory consumption.
> [NATS] Extend to support in-memory stream

- driver-redis/pom.xml
- driver-redis/src/main/java/io/openmessaging/benchmark/driver/redis/RedisBenchmarkConsumer.java
- driver-redis/src/main/java/io/openmessaging/benchmark/driver/redis/RedisBenchmarkDriver.java
This is a simple "homework" PR to update Jedis to the latest available version, while ensuring it keeps working as expected WRT the client breaking changes. 
Further PRs should come WRT further capabilities of redis that are not configurable now (cluster, resp3, pipelining, etc... ). 
To easily try out:
```
$ git clone https://github.com/redis-performance/openmessaging-benchmark --branch redis.jedis.5
$ cd openmessaging-benchmark
$ mvn install
$ bin/benchmark --drivers driver-redis/redis.yaml workloads/1-topic-1-partition-1kb.yaml
```
> Bumped Jedis to v5.0.0 - fixed breaking changes from v3.7.0

- benchmark-framework/pom.xml
- driver-pravega/README.md
- driver-pravega/deploy/deploy.yaml
- driver-pravega/deploy/provision-pravega-aws.tf
- driver-pravega/deploy/terraform.tfvars
- driver-pravega/deploy/vars.yaml
- driver-pravega/pom.xml
**Change log description**
Updates Pravega libraries and deployment scripts.
**Purpose of the change**
Fixes #391.
**What the code does**
- Updates Pravega and Bookkeeper versions at the server side when deploying, as well as the Pravega client library for the benchmark.
- Updates the AMI used and the default types of images.
- Updates the deployment script to adapt to few changes: i) docker installation, ii) `cloudalchemy.node_exporter` naming, iii) device names, iv) Bookkeeper initialization command.
- Updated the README to reflect previous changes.
- Set scope `provided` to `driver-nats-streaming`. The reason for doing that is that `driver-nats-streaming` is transitively importing a very old version of Google Protobuf (`3.9.1` - Aug 06, 2019). Pravega also uses Google Protobuf. When …
> Issue 391: Update Pravega library versions and deployment script

- driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkDriver.java
**BUG REPORT**
the condition that the bug triggers:
when install this project  use this command `mvn install  `
***Describe the bug***
Fixed for 'Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.25.0:check (check) on project driver-rocketmq: The following files had format violations: [ERROR] src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkDriver.java'
***Screenshots***
***Suggestion***
how to avoid the problem from happening again? 
please execute this command `mvn spotless:apply` to format the code before push the commit
> Fixed for project driver-rocketmq had format violations

- benchmark-framework/src/main/java/io/openmessaging/benchmark/worker/jackson/HistogramSerializer.java
- benchmark-framework/src/test/java/io/openmessaging/benchmark/worker/jackson/HistogramSerDeTest.java
- driver-rocketmq/src/main/java/io/openmessaging/benchmark/driver/rocketmq/RocketMQBenchmarkDriver.java
When we serialize a histogram to a byte array, the intermediate
ByteBuffer that we pass may be too small which may result in silent
truncation of the encoded histogram.
This will manifest on the driver side as a decoding failure. However,
because the driver side retries this request on failure, it will attempt
to get the histogram from the remote worker a second time but 
histogram reads are "destructive" - they clear the source histogram.
So the second read will succeed because the histogram is much 
smaller (it is almost empty), but it leads to only sampling about 1
second worth of data at the end of the test.
This change detects this case and grows the buffer by a
factor of 2 until it fits.
Fixes https://github.com/openmessaging/benchmark/issues/369.
> Grow buffer if histogram can't fit

- driver-kafka/deploy/hdd-deployment/templates/kafka.service
- driver-kafka/deploy/ssd-deployment/templates/kafka.service
Mismatched single and double quotes caused KAFKA_JVM_PERFORMANCE_OPTS configuration to not take effect.
This was introduced in a commit 84a29dd928ffe879f5d8a2cc08f3d816867fd495 6 years ago.
> fix(driver-kafka): Fix the ineffective `KAFKA_JVM_PERFORMANCE_OPTS`

- driver-kafka/deploy/hdd-deployment/alicloud/deploy.yaml
- driver-kafka/deploy/hdd-deployment/deploy.yaml
- driver-kafka/deploy/ssd-deployment/alicloud/deploy.yaml
- driver-kafka/deploy/ssd-deployment/deploy.yaml
- driver-kafka/pom.xml
Some known issues with current version:
- PEM files cannot be used because of a bug.
> kafka: chore: upgrade kafka version

- bin/benchmark
- bin/benchmark-worker
- pom.xml
OMB benchmark worker should enable Netty's optimized direct bytebuffer support. 
This PR sets the required JVM options for the benchmark-worker.
> Enable optimized Netty direct bytebuffer reflection access

- driver-kafka/src/main/java/io/openmessaging/benchmark/driver/kafka/KafkaBenchmarkDriver.java
The steps to assign the Zone ID to the Kafka client ID
1. Set JVM options when starting the benchmark worker, e.g. JVM_OPTS=-Dzone.id=usw1-az1
2. Set the client.id to the commonConfig section in the Kafka driver file, e.g. client.id=xxx-{zone.id}
> Support set client.id with Zone ID for Kafka driver
